### ISSUE TITLE
如何获取到截取的图片

### ISSUE THREAD

**Issue by MysteryRan** [isee15/QQ-capture-screen-on-mac#1]

**Comment by isee15** [comment]
最简单的是直接从剪贴板里面获取到截到的图片
要真正用则需要classdump头文件，找到delegate或者通知的地方
新版qq已经换成JTCaptureManager实现了

**Comment by isee15** [comment]
最新的代码里面包含了JTCaptureManager的Demo

**Comment by MysteryRan** [comment]
谢谢,不过不懂怎么hook通知的。

**Comment by isee15** [comment]
> 谢谢,不过不懂怎么hook通知的。

就是基本的swizzle操作
